name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: omersade

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Generate version tag
        id: vars
        run: echo "VERSION=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Build frontend image
        run: docker build -t $DOCKER_REPO/frontend:${{ env.VERSION }} ./frontend

      - name: Build backend image
        run: docker build -t $DOCKER_REPO/backend:${{ env.VERSION }} ./backend

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Perform health check on frontend
        run: curl -f http://localhost:8081 || exit 1

      - name: Tag and push frontend image
        run: |
          docker tag $DOCKER_REPO/frontend:${{ env.VERSION }} $DOCKER_REPO/frontend:latest
          docker push $DOCKER_REPO/frontend:${{ env.VERSION }}
          docker push $DOCKER_REPO/frontend:latest

      - name: Tag and push backend image
        run: |
          docker tag $DOCKER_REPO/backend:${{ env.VERSION }} $DOCKER_REPO/backend:latest
          docker push $DOCKER_REPO/backend:${{ env.VERSION }}
          docker push $DOCKER_REPO/backend:latest

      - name: Clean up
        run: docker compose down

